name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: signal-space-rs
      - uses: actions/checkout@v4
        with:
          repository: signal-space/signal-space-spec
          path: signal-space-spec
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
        working-directory: signal-space-rs
      - run: cargo test
        working-directory: signal-space-rs
      - run: cargo test --features lazily-runtime
        working-directory: signal-space-rs
