name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-crates:
    runs-on: ubuntu-latest
    environment: crates
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: signal-space/signal-space-spec
          path: signal-space-spec
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
